[package]
name = "resin-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features=["derive"] }
nostro2.workspace = true
nostro2-signer.workspace = true
serde_json.workspace = true
sha2.workspace = true
