[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = ["../resin-core", "src", "index.html", "styles"]

[serve]
port = 8000
open = false

[[hooks]]
stage = "pre_build"
command = "bash"
command_arguments = [
    "-c",
    "tailwindcss4 -i styles/input.css -o styles/output.css"
]
