[package]
name = "resin-server"
version = "0.1.0"
edition = "2021"

[dependencies]
upload-things = "0.1.2"
nostro2 = "0.3.1"
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.12"
serde_json = "1"
nostro2-signer = "0.1.0"
nostro2-relay = "0.1.0"
