[package]
name = "listing-test"
version = "0.1.0"
edition = "2021"

[dependencies]
nostro2-relay = "0.1.0"
nostro2-signer = "0.1.0"
rand = "0.9.0"
resin-core = { path = "../resin-core" }
tokio = { version = "1.44.1", features = ["full"] }
